baloti_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "baloti_auth"
urlpatterns = [
    path('login/', BalotiLoginView.as_view(
        ), name="login"),
    path('logout/', auth_views.LogoutView.as_view(
                    ), name='logout'),
    path('signup/', BalotiSignupView.as_view(
        ), name="signup"),
    path('signup/mailsent/', BalotiSignupMailView.as_view(
        ), name="signup_mail"),
    path('modalsignup/mailsent/', BalotiModalSignupMailView.as_view(
        ), name="modalsignup_mail"),
    path(
        'change-password/',
        BalotiPasswordChangeView.as_view(
            template_name='change_password.html',
        ),
        name='change-password'
    ),
    path('password-reset/',
         BalotiPasswordResetView.as_view(
             template_name='password_reset.html',
             email_template_name='password_reset_email.html',
             html_email_template_name="password_reset_email.html",
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         BalotiPasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('delete/profile', BalotiDeleteProfileView.as_view(), name='deleteProfile'),
]

baloti_djelectionguard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', BalotiIndexView.as_view()),
    path('disclaimer', BalotiDisclaimerView.as_view()),
    path('about-us', BalotiAboutUsView.as_view()),
    path('contest/list/', BalotiContestListView.as_view()),
    path('contest/<str:id>', BalotiContestDetailView.as_view(), name='ContestDetails'),
    path('contest/vote/choices/<str:id>', BalotiContestChoicesView.as_view(), name='VoteChoices'),
    path('vote/<str:id>', VoteView.as_view(), name='casteVote'),
    path('contest/detail/<str:id>', BalotiContestDetailView.as_view(), name='viewContestDetails'),
    path('contest/result/<str:id>', BalotiContestResultView.as_view(), name='viewContestResult'),
    path('anonymous/vote/', BalotiAnonymousVoteView.as_view(), name='anonymousVote'),
    path('contest/vote/success/<str:id>', VoteSuccessView.as_view(), name='VoteSuccess'),
]

baloti_djelectionguard/urls/urls.py
from django.urls import path
from ..views import *

app_name = "baloti_djelectionguard"
urlpatterns = [
    path('', BalotiIndexView.as_view(), name="Index"),
    path('success/<str:process>', BalotiIndexView.as_view(), name="ProcessSuccessIndex"),
    path('contest/list/', BalotiContestListView.as_view(), name='ContestList'),
    path('contest/list/<str:sort>', BalotiContestListSortView.as_view(), name='ContestSortedList'),
    path('contest/<str:id>', BalotiContestDetailView.as_view(), name='ContestDetails'),
    path('contest/vote/choices/<str:id>', BalotiContestChoicesView.as_view(), name='VoteChoices'),
    path('vote/<str:id>', VoteView.as_view(), name='casteVote'),
    path('contest/detail/<str:id>', BalotiContestDetailView.as_view(), name='viewContestDetails'),
    path('contest/result/<str:id>', BalotiContestResultView.as_view(), name='viewContestResult'),
    path('anonymous/vote/', BalotiAnonymousVoteView.as_view(), name='anonymousVote'),
    path('contest/vote/success/<str:id>', VoteSuccessView.as_view(), name='VoteSuccess'),
]

electeez_common/urls.py
from django import http
from django.contrib import admin, messages
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.urls import include, path, reverse
from django.utils.decorators import method_decorator
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.templatetags.static import static as static_url
from django.contrib.auth import views as auth_views

from djlang.utils import gettext as _
from baloti_djelectionguard import cron_jobs

urlpatterns = [
    url(r'^favicon\.ico$', generic.RedirectView.as_view(url='/static/images/favicon.ico')),
]

cron_jobs.initialize_cron()

@method_decorator(csrf_exempt, name='dispatch')
class HomeView(generic.TemplateView):
    def dispatch(self, request, *args, **kwargs):
        url = reverse('login')

        if request.user.is_authenticated:
            url = reverse('parentcontest_list')

        elif home_page := getattr(settings, 'STATIC_HOME_PAGE', None):
            url = static_url(home_page)

        elif template := getattr(settings, 'HOME_TEMPLATE', None):
            self.template_name = template
            return super().dispatch(request, *args, **kwargs)

        return http.HttpResponseRedirect(url)

    def post(self, request, *args, **kwargs):
        if 'inputEmail' in request.POST:
            messages.success(
                request,
                _('You have successfully subscribed to %(app)s mailing list',
                    app=_('Neuilly Vote')
                )
            )
        return self.get(request, *args, **kwargs)


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('electeez_auth.urls')),
    path('contest/', include('djelectionguard.urls')),
    path('tezos/', include('djelectionguard_tezos.views')),
    path('track/', include('djelectionguard_tracker.views')),
    path('lang/', include('djlang.views')),
    path('electis/', HomeView.as_view(), name='home'),
    path('baloti/', include(('baloti_auth.urls', 'baloti'), namespace="baloti"), name='baloti'),
    path('baloti/', include(('baloti_djelectionguard.urls.urls', 'baloti_djelectionguard'), namespace="baloti_djelectionguard"), name='baloti_djelectionguard'),
    path('', include(('baloti_djelectionguard.urls.general_urls', 'general_djelectionguard'), namespace="general_djelectionguard"), name='general_djelectionguard'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
)

if settings.DEBUG:
    urlpatterns.append(
        path('bundles/', include('ryzom_django.bundle')),
    )


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns('/static/')
urlpatterns += staticfiles_urlpatterns('/public/electis')
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

neuilly/urls.py
from electeez_common.urls import *


class LegalView(generic.TemplateView):
    template_name = 'legal'


class DataPolicyView(generic.TemplateView):
    template_name = 'policy'


class CookieView(generic.TemplateView):
    template_name = 'cookies'


class FAQView(generic.TemplateView):
    template_name = 'faq'


urlpatterns += i18n_patterns(
    path('legal/', LegalView.as_view(), name='legal'),
    path('policy/', DataPolicyView.as_view(), name='policy'),
    path('cookies/', CookieView.as_view(), name='cookies'),
    path('faq/', FAQView.as_view(), name='faq'),
)

baloti_djelectionguard/views.py
import json
from django.shortcuts import render
from djelectionguard.models import Contest, Candidate, ParentContest
from .models import ParentContesti18n, Contesti18n
from django.db.models import ObjectDoesNotExist, Q
from django.http import *
from django.views.generic import TemplateView
from djlang.utils import gettext as _
from electeez_common.components import *
import hashlib
from django.utils.translation import get_language
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from electeez_auth.models import User
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from deep_translator import GoogleTranslator
from djlang.models import Language

def getParentDetails(parent):
        """
        Args:
            @param id - parent

        Returns:
            @return array
        """
        data = {
            'name': parent.name,
            'id': parent.parent_contest_id.uid,
            'iso':parent.language.iso,
            'date': parent.parent_contest_id.start.date(),
            'end_date': parent.parent_contest_id.end.date(),
            'month': parent.parent_contest_id.start.strftime('%B'),
            'year': parent.parent_contest_id.start.strftime('%Y'),
            'status': parent.parent_contest_id.status,
            }
        return data

class BalotiIndexView(TemplateView):
    """
    Index view.
    """

    def get(self, request, process=None):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns index.html html file
        """
        contests = []
        current_language = get_language()
        open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open", language__iso=current_language).order_by('-parent_contest_id__start')
        contests.append(getParentDetails(open_contests[0])) if open_contests else None
        closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed", language__iso=current_language).order_by('-parent_contest_id__end')
        contests.append(getParentDetails(closed_contests[0])) if closed_contests else None
        if process == 'changepassword':
            return render(request, 'index.html',{"contests": contests, "changepassword":True})
        elif process == 'logout':
            return render(request, 'index.html',{"contests": contests, "logout":True})
        elif process == 'login':
            return render(request, 'index.html',{"contests": contests, "login":True})
        elif process == 'registration':
            return render(request, 'index.html',{"contests": contests, "registration":True})
        elif process == None:
            return render(request, 'index.html',{"contests": contests})
        return render(request, 'index.html',{"contests": contests})


class BalotiNewsView(TemplateView):
    """
    News View
    """
    template_name = "news.html"

class BalotiDisclaimerView(TemplateView):
    """
    Disclaimer View
    """
    template_name = "disclaimer.html"

class BalotiImprintView(TemplateView):
    """
    Imprint View
    """
    template_name = "imprint.html"

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns imprint.html html file
        """
        return render(request, 'imprint.html')

class BalotiDataPrivacyView(TemplateView):
    """
    Data Privacy View
    """
    template_name = "data_privacy.html"

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns data_privacy.html html file
        """
        return render(request, 'data_privacy.html')



class BalotiAboutUsView(TemplateView):
    """
    AboutUs View
    """
    template_name = "about-us.html"

class BalotiInfoView(TemplateView):
    """
    Info View
    """

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns landing-en.html html file
        """
        return render(request, 'landing-en.html')

    def post(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns landing-en.html html file
        """
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        email_from = settings.DEFAULT_FROM_EMAIL
        email_to = 'baloti@pitsolutions.ch'
        if firstname and lastname and email and subject and message:
            merge_data = {
                        'firstname': firstname,
                        'lastname': lastname,
                        'email': email,
                        'message': message
                        }
            html_body = render_to_string("contactinfo_mail.html", merge_data)

            message = EmailMultiAlternatives(
               subject=subject,
               body="mail testing",
               from_email=email_from,
               to=[email_to],
            )
            message.attach_alternative(html_body, "text/html")
            message.send()
            responseData = {}
            return HttpResponse(json.dumps(responseData), content_type="application/json")
        else:
            return HttpResponseBadRequest()


class BalotiContestListView(TemplateView):
    """
    Contest List View
    """

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns contest_list.html html file
        """
        open_list = []
        closed_list = []
        current_language = get_language()
        open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open",language__iso=current_language).order_by('-parent_contest_id__start')
        for open_contest in open_contests:
            open_list.append(getParentDetails(open_contest))
        closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed",language__iso=current_language).order_by('-parent_contest_id__end')
        for closed_contest in closed_contests:
            closed_list.append(getParentDetails(closed_contest))
        return render(request, 'contest_list.html',{"open_contests": open_list, "closed_contests": closed_list})

class BalotiContestListSortView(TemplateView):
    """
    Contest List View
    """

    def get(self, request, sort):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns contest_list.html html file
        """
        open_list = []
        closed_list = []
        current_language = get_language()
        if sort == 'asc':
            open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open",language__iso=current_language).order_by('parent_contest_id__actual_start')
            closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed",language__iso=current_language).order_by('parent_contest_id__actual_end')
        else:
            open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open", language__iso=current_language).order_by('-parent_contest_id__actual_start')
            closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed", language__iso=current_language).order_by('-parent_contest_id__actual_end')
        for open_contest in open_contests:
            open_list.append(getParentDetails(open_contest))
        for closed_contest in closed_contests:
            closed_list.append(getParentDetails(closed_contest))
        return render(request, 'contest_list.html',{"open_contests": open_list, "closed_contests": closed_list})


class BalotiContestDetailView(TemplateView):
    """
    Contest Detail View
    """
    
    def get(self, request, id):
        """
        Args:
            request (Request): Http request object
            id: Contest UID

        Returns:
            html : returns contest_details.html html file
        """
        current_language = get_language()
        contest = ParentContesti18n.objects.filter(parent_contest_id__uid=id, language__iso=current_language)
        child_contests = Contesti18n.objects.filter(
                parent=contest.first().parent_contest_id,
                language__iso=current_language
                ).distinct('id')
        date_string = contest.first().parent_contest_id.end.strftime("%m/%d/")
        return render(request, 'contest_details.html',{"contest": contest.first(), "date": str(date_string), "child_contests": child_contests})


class BalotiContestResultView(TemplateView):
    """
    Contest Result View
    """

    def get(self, request, id):
        """
        Args:
            request (Request): Http request object
            id: Contest UID

        Returns:
            html : returns contest_results.html html file
        """
        current_language = get_language()
        contest = Contesti18n.objects.filter(contest_id=id, language__iso=current_language).first()
        return render(request, 'contest_results.html',{"contest": contest})


class BalotiContestChoicesView(TemplateView):
    """
    Contest Choices View
    """
    
    def get(self, request, id):
        """
        Args:
            request (Request): Http request object
            id: Candidate UID

        Returns:
            html : returns contest_vote_choices.html html file
        """
        data = []
        current_language = get_language()
        language = Language.objects.filter(iso=current_language).first()
        contest = Contesti18n.objects.filter(contest_id=id, language__iso=current_language)
        if contest:

baloti_djelectionguard/templates/choice-no-login.html
{% extends 'layout/base.html' %}
{% load static %}
{% block body %}  
{% load static i18n %}

<section class="app-choice app-body-bg">
    <div class="container">
        <!-- <a class="btn btn-link btn-back" href="javascript:window.history.back()"> <span class="app-icon icon-arrow-right"></span> <span>BACK</span> </a> -->
        <div class="row">
            <div class="col-sm-12 col-lg-7 mx-auto">
                <div class="app-card app-card--lg app-card--nopad">
                    <div class="app-card__header border-btm">
                        <p class="app-card__header-title">{% trans "Make your choice" %}</p>
                        <p class="app-sm-text text-medium">{{contest.name}}</p>
                    </div>
                    {% csrf_token %}
                    <div class="app-card__body">
                        <ul class="app-checkboxlist list-unstyled">
                            {% for i in candidates %}
                                <li class="app-form__control checkbox">
                                    <input class="form-check-input" checked type="radio" value={{i.id}} id={{i.id}} dataname={{i.name}} name="choice">
                                    <label class="form-check-label" for="{{i.id}}">{{i.name}}</label>
                                </li>
                            {% endfor %}
                            {{i.id}}
                        </ul>
                        <div class="app-card__btngroup d-flex align-items-center justify-content-between">
                            <a class="btn btn-default" href="javascript:window.history.back()">{% trans "BACK" %}</a>
                            <button class="btn btn-primary" id="showBalletModal">{% trans "CREATE BALLOT" %}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<!-- <div class="app-social-follow">
    <a href="#" class="app-icon icon-facebook"></a>
    <a href="#" class="app-icon icon-twiter"></a>
    <span class="app-social-follow__txt">FOLLOW US ON</span>
</div> -->

  
<!-- Modal -->
<div class="modal fade app-modal" id="createballet" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content d-none" id="appLogin">
            <div class="app-login__box">
                {% csrf_token %}
                <!-- <div class="app-login__logo">
                    <img src="/static/images/logo.svg" alt="">
                </div> -->
                <h3 class="app-login__heading text-bold">
                    {% trans "Login Required!" %}
                </h3>
                <p class="app-login__subhead">{% trans "Please Login to your account to continue voting" %}</p>

                <div class="app-login__btn-group">
                    <a class="btn btn-facebook btn-block" id="fbloginBtn" href="{% url 'social:begin' 'facebook' %}?next="><span class="app-icon icon-facebook-box"></span> <span>{% trans "Continue with Facebook" %}</span></a>
                </div>
                
                <p class="app-sepeartor"><span>or</span></p>
                <div class="app-form" id="idLogin">
                    <div class="app-form__control">
                        <input id="id_username" name="username" 
                                   type="text" class="form-control" placeholder=" " required>
                        <label for="id_username" class="app-form__label">{% trans "Email address" %}</label>
                    </div>
                    <div class="app-form__control app-form__control--password">
                        <input id="id_password" name="password" 
                                   type="password" class="form-control" placeholder=" " required>
                        <label for="id_password" class="app-form__label">{% trans "Password" %}</label>
                        <span id="showHidePassword" class="app-icon icon-view show-hide-password"></span>
                    </div>

                    <p class="label label-danger d-none" id="login_error">
                        {% trans "Your username and password didn't match. Please try again." %}
                    </p>
                    <a href={% url 'baloti_auth:password_reset' %} class="app-link app-link--forget-password">{%trans "Forgot password?" %}</a>
                    <button type="button" isloggedIn="false" id="loginBtn" class="btn btn-primary btn-block btn-md--small">{% trans "CONTINUE" %}</button>
                    <p class="app-login__createaccount"><span>{% trans "Not registered yet?" %}</span> <a id="idCreateAccount"  href="#" class="app-link" signup="true">{% trans "Create an account now" %}</a> </p>
                </div>

                <button type="button" id="logincloseBtn" class="btn btn-default mx-auto" data-dismiss="modal">{% trans "CLOSE" %}</button>
            </div>
        </div>


        <div class="modal-content d-none" id="idSignup">
            <div class="app-login__box">
                {% csrf_token %}

                <h3 class="app-login__heading text-bold">
                    {% trans "Create account!" %}
                </h3>
                <p class="app-login__subhead">{% trans "You can register with your social login or email address." %}</p>

                <div class="app-login__btn-group">
                    <a class="btn btn-facebook btn-block" id="fbloginBtn" href="{% url 'social:begin' 'facebook' %}?next="><span class="app-icon icon-facebook-box"></span> <span>{% trans "Continue with Facebook" %}</span></a>
                </div>
                <p class="app-sepeartor"><span>or</span></p>

                <div class="app-form">
                    <div class="app-form__control">
                        {% if email %}
                        <input type="email" name="email" id="exampleInputEmail1" value={{email}} aria-describedby="emailHelp" placeholder=" "/>
                        {% else %}
                        <input type="email" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder=" "/>
                        {% endif %}
                        <label for="exampleInputEmail1" class="app-form__label">{% trans "Email address" %}</label>
                        <div class="app-form__msg">
                            <p class="text-danger m-0">{{error}}</p>
                            <p>{% trans "We will send you the registration link to the email address you entered." %}</p>
                        </div>
                    </div>
                    <p class="label label-danger d-none" id="signup_error">
                        {% trans "This email has already been registered." %}
                    </p>
                     <p class="label label-danger d-none" id="signup_nofielderror">
                        {% trans "Users must have an email address." %}
                    </p>
                    <button id="signupBtn" class="btn btn-primary btn-block btn-md--small">{% trans "SEND" %}</button>
                    <p class="app-login__createaccount"><span>{% trans "Already have an account?" %}</span> <a id="idButtonLogin" href="#" class="app-link">{% trans "Login here!" %}</a> </p>
                </div>
                <button type="button" id="logincloseBtn" class="btn btn-default mx-auto" data-dismiss="modal">{% trans "CLOSE" %}</button>
            </div>
        </div>

        <div class="modal-content d-none" id="idsignupSuccess">
            <div class="app-login__box">
                <div class="app-login__logo">
                    <img src="/static/images/logo.svg" alt="">
                </div>
                <h3 class="app-login__heading">
                    {% trans "Mail sent!" %}
                </h3>
                <p class="app-login__subhead">{% trans "Please check your inbox to get the registration informations. Thank you." %}</p>

                <div class="text-center">
                    <div class="img-block">
                        <img src="/static/images/login-complete.svg" alt="">
                    </div>
                    <a class="btn btn-primary btn-md--small" id="idButtonLoginAfterSuccess" href="#!">{% trans "LOGIN NOW" %}</a>
                </div>
            </div>
        </div>

        <div class="modal-content d-none app-modal--success" id="success">
            <div class="modal-body text-center">
                <div class="app-bg app-result-wrap app-modal--success">
                    <img src="/static/images/vote-success.png" alt="">
                    <p class="app-h5 text-success text-bold">{% trans "Success!" %}</p>
                    <p class="app-h6 m-0">{% trans "Your Choice Added Successfully" %}</p>
                </div>
                <div class="modal-result app-result-wrap">
                    <p class="app-p">{% trans "Thank for voting at the Referendum and be a part of Direct Democracy." %}</p>
                    <p class="app-h6 text-danger">{% trans "The results will be announced on" %}</p>
                    <p class="app-resultdate">{{contest.contest_id.end|date:"d.m.Y"}}</p>
                    <p class="app-p">{% trans "and you will be notified via email." %}</p>
                    <button class="btn btn-default mx-auto"><a href={% url 'baloti_djelectionguard:ContestDetails' contest.parent.uid %}>{% trans "BACK TO REFERENDUM" %}</a></button>
                </div>
            </div>
        </div>

        <!-- Modal Warning-->
        <div class="modal-content d-none" id="alreadyVoted">
            <div class="modal-body text-center">
                <div class="app-bg app-result-wrap">
                    <img src="/static/images/vote-completed.png" alt="">
                    <p class="app-h5 text-warning text-bold">{% trans "You've already voted!!" %}</p>
                </div>
                <div class="modal-result app-result-wrap">
                    <p class="app-p">{% trans "No problem, there are other referendums you can vote for." %}</p>
                    <p class="app-h6 text-danger">{% trans "The results will be announced on" %}</p>
                    <p class="app-resultdate">{{contest.contest_id.end|date:"d.m.Y"}}</p>
                    <p class="app-p">{% trans "and you will be notified via email." %}</p>
                    <button class="btn btn-default mx-auto"><a href={% url 'baloti_djelectionguard:ContestDetails' contest.parent.uid %}>{% trans "BACK TO REFERENDUM" %}</a></button>
                </div>
            </div>
        </div>

        <div class="modal-content app-bg" id="confirmVote">
            <div class="modal-header">
                <h5 class="modal-title text-bold" id="exampleModalLongTitle">{% trans "Confirm your selection" %} </h5>
            </div>
            <div class="modal-body text-center">
                <div class="app-modal__msgbox text-bold text-uppercase">
                    <span id="choice_input"></span>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" id="closeBtn" class="btn btn-default" data-dismiss="modal">{% trans "CANCEL" %}</button>
                <button type="button" isloggedIn="false" id="confirmBtn" class="btn btn-primary">{% trans "CONFIRM" %}</button>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

baloti_djelectionguard/templates/contactinfo_mail.html
{% load static %}
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baloti</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="app">
        <section class="app-login">
            <div class="app-login__img">
                <img src="/static/images/login-img.png" alt="">
            </div>
            <div class="container">
                <div class="row flex-row-reverse">
                    <div class="col-sm-12 col-xl-5">
                        <div class="app-login__box">
                            <div class="app-login__logo">
                                <img src="/static/images/logo.svg" alt="">
                            </div>
                            <h3 class="app-login__heading">
                                {% trans "Contact Information" %}
                            </h3>
                            <p class="app-sepeartor text-center"><span>{{message}}</span></p>
                            <p class="app-sepeartor text-center"><span>{% trans "First Name:" %} {{firstname}}</span></p>
                            <p class="app-sepeartor text-center"><span>{% trans "Last Name: " %} {{lastname}}</span></p>
                            <p class="app-sepeartor text-center"><span>{% trans "Email:" %} {{email}}</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>