baloti_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "baloti_auth"
urlpatterns = [
    path('login/', BalotiLoginView.as_view(
        ), name="login"),
    path('logout/', auth_views.LogoutView.as_view(
                    ), name='logout'),
    path('signup/', BalotiSignupView.as_view(
        ), name="signup"),
    path('signup/mailsent/', BalotiSignupMailView.as_view(
        ), name="signup_mail"),
    path('modalsignup/mailsent/', BalotiModalSignupMailView.as_view(
        ), name="modalsignup_mail"),
    path(
        'change-password/',
        BalotiPasswordChangeView.as_view(
            template_name='change_password.html',
        ),
        name='change-password'
    ),
    path('password-reset/',
         BalotiPasswordResetView.as_view(
             template_name='password_reset.html',
             email_template_name='password_reset_email.html',
             html_email_template_name="password_reset_email.html",
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         BalotiPasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('delete/profile', BalotiDeleteProfileView.as_view(), name='deleteProfile'),
]

baloti_djelectionguard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', BalotiIndexView.as_view()),
    path('disclaimer', BalotiDisclaimerView.as_view()),
    path('about-us', BalotiAboutUsView.as_view()),
    path('contest/list/', BalotiContestListView.as_view()),
    path('contest/<str:id>', BalotiContestDetailView.as_view(), name='ContestDetails'),
    path('contest/vote/choices/<str:id>', BalotiContestChoicesView.as_view(), name='VoteChoices'),
    path('vote/<str:id>', VoteView.as_view(), name='casteVote'),
    path('contest/detail/<str:id>', BalotiContestDetailView.as_view(), name='viewContestDetails'),
    path('contest/result/<str:id>', BalotiContestResultView.as_view(), name='viewContestResult'),
    path('anonymous/vote/', BalotiAnonymousVoteView.as_view(), name='anonymousVote'),
    path('contest/vote/success/<str:id>', VoteSuccessView.as_view(), name='VoteSuccess'),
]

baloti_djelectionguard/urls/urls.py
from django.urls import path
from ..views import *

app_name = "baloti_djelectionguard"
urlpatterns = [
    path('', BalotiIndexView.as_view(), name="Index"),
    path('success/<str:process>', BalotiIndexView.as_view(), name="ProcessSuccessIndex"),
    path('contest/list/', BalotiContestListView.as_view(), name='ContestList'),
    path('contest/list/<str:sort>', BalotiContestListSortView.as_view(), name='ContestSortedList'),
    path('contest/<str:id>', BalotiContestDetailView.as_view(), name='ContestDetails'),
    path('contest/vote/choices/<str:id>', BalotiContestChoicesView.as_view(), name='VoteChoices'),
    path('vote/<str:id>', VoteView.as_view(), name='casteVote'),
    path('contest/detail/<str:id>', BalotiContestDetailView.as_view(), name='viewContestDetails'),
    path('contest/result/<str:id>', BalotiContestResultView.as_view(), name='viewContestResult'),
    path('anonymous/vote/', BalotiAnonymousVoteView.as_view(), name='anonymousVote'),
    path('contest/vote/success/<str:id>', VoteSuccessView.as_view(), name='VoteSuccess'),
]

electeez_common/urls.py
from django import http
from django.contrib import admin, messages
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.urls import include, path, reverse
from django.utils.decorators import method_decorator
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.templatetags.static import static as static_url
from django.contrib.auth import views as auth_views

from djlang.utils import gettext as _
from baloti_djelectionguard import cron_jobs

urlpatterns = [
    url(r'^favicon\.ico$', generic.RedirectView.as_view(url='/static/images/favicon.ico')),
]

cron_jobs.initialize_cron()

@method_decorator(csrf_exempt, name='dispatch')
class HomeView(generic.TemplateView):
    def dispatch(self, request, *args, **kwargs):
        url = reverse('login')

        if request.user.is_authenticated:
            url = reverse('parentcontest_list')

        elif home_page := getattr(settings, 'STATIC_HOME_PAGE', None):
            url = static_url(home_page)

        elif template := getattr(settings, 'HOME_TEMPLATE', None):
            self.template_name = template
            return super().dispatch(request, *args, **kwargs)

        return http.HttpResponseRedirect(url)

    def post(self, request, *args, **kwargs):
        if 'inputEmail' in request.POST:
            messages.success(
                request,
                _('You have successfully subscribed to %(app)s mailing list',
                    app=_('Neuilly Vote')
                )
            )
        return self.get(request, *args, **kwargs)


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('electeez_auth.urls')),
    path('contest/', include('djelectionguard.urls')),
    path('tezos/', include('djelectionguard_tezos.views')),
    path('track/', include('djelectionguard_tracker.views')),
    path('lang/', include('djlang.views')),
    path('electis/', HomeView.as_view(), name='home'),
    path('baloti/', include(('baloti_auth.urls', 'baloti'), namespace="baloti"), name='baloti'),
    path('baloti/', include(('baloti_djelectionguard.urls.urls', 'baloti_djelectionguard'), namespace="baloti_djelectionguard"), name='baloti_djelectionguard'),
    path('', include(('baloti_djelectionguard.urls.general_urls', 'general_djelectionguard'), namespace="general_djelectionguard"), name='general_djelectionguard'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
)

if settings.DEBUG:
    urlpatterns.append(
        path('bundles/', include('ryzom_django.bundle')),
    )


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns('/static/')
urlpatterns += staticfiles_urlpatterns('/public/electis')
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

neuilly/urls.py
from electeez_common.urls import *


class LegalView(generic.TemplateView):
    template_name = 'legal'


class DataPolicyView(generic.TemplateView):
    template_name = 'policy'


class CookieView(generic.TemplateView):
    template_name = 'cookies'


class FAQView(generic.TemplateView):
    template_name = 'faq'


urlpatterns += i18n_patterns(
    path('legal/', LegalView.as_view(), name='legal'),
    path('policy/', DataPolicyView.as_view(), name='policy'),
    path('cookies/', CookieView.as_view(), name='cookies'),
    path('faq/', FAQView.as_view(), name='faq'),
)

baloti_djelectionguard/views.py
import json
from django.shortcuts import render
from djelectionguard.models import Contest, Candidate, ParentContest
from .models import ParentContesti18n, Contesti18n
from django.db.models import ObjectDoesNotExist, Q
from django.http import *
from django.views.generic import TemplateView
from djlang.utils import gettext as _
from electeez_common.components import *
import hashlib
from django.utils.translation import get_language
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from electeez_auth.models import User
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from deep_translator import GoogleTranslator
from djlang.models import Language

def getParentDetails(parent):
        """
        Args:
            @param id - parent

        Returns:
            @return array
        """
        data = {
            'name': parent.name,
            'id': parent.parent_contest_id.uid,
            'iso':parent.language.iso,
            'date': parent.parent_contest_id.start.date(),
            'end_date': parent.parent_contest_id.end.date(),
            'month': parent.parent_contest_id.start.strftime('%B'),
            'year': parent.parent_contest_id.start.strftime('%Y'),
            'status': parent.parent_contest_id.status,
            }
        return data

class BalotiIndexView(TemplateView):
    """
    Index view.
    """

    def get(self, request, process=None):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns index.html html file
        """
        contests = []
        current_language = get_language()
        open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open", language__iso=current_language).order_by('-parent_contest_id__start')
        contests.append(getParentDetails(open_contests[0])) if open_contests else None
        closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed", language__iso=current_language).order_by('-parent_contest_id__end')
        contests.append(getParentDetails(closed_contests[0])) if closed_contests else None
        if process == 'changepassword':
            return render(request, 'index.html',{"contests": contests, "changepassword":True})
        elif process == 'logout':
            return render(request, 'index.html',{"contests": contests, "logout":True})
        elif process == 'login':
            return render(request, 'index.html',{"contests": contests, "login":True})
        elif process == 'registration':
            return render(request, 'index.html',{"contests": contests, "registration":True})
        elif process == None:
            return render(request, 'index.html',{"contests": contests})
        return render(request, 'index.html',{"contests": contests})


class BalotiNewsView(TemplateView):
    """
    News View
    """
    template_name = "news.html"

class BalotiDisclaimerView(TemplateView):
    """
    Disclaimer View
    """
    template_name = "disclaimer.html"

class BalotiImprintView(TemplateView):
    """
    Imprint View
    """
    template_name = "imprint.html"

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns imprint.html html file
        """
        return render(request, 'imprint.html')

class BalotiDataPrivacyView(TemplateView):
    """
    Data Privacy View
    """
    template_name = "data_privacy.html"

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns data_privacy.html html file
        """
        return render(request, 'data_privacy.html')



class BalotiAboutUsView(TemplateView):
    """
    AboutUs View
    """
    template_name = "about-us.html"

class BalotiInfoView(TemplateView):
    """
    Info View
    """

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns landing-en.html html file
        """
        return render(request, 'landing-en.html')

    def post(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns landing-en.html html file
        """
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        email_from = settings.DEFAULT_FROM_EMAIL
        email_to = 'baloti@pitsolutions.ch'
        if firstname and lastname and email and subject and message:
            merge_data = {
                        'firstname': firstname,
                        'lastname': lastname,
                        'email': email,
                        'message': message
                        }
            html_body = render_to_string("contactinfo_mail.html", merge_data)

            message = EmailMultiAlternatives(
               subject=subject,
               body="mail testing",
               from_email=email_from,
               to=[email_to],
            )
            message.attach_alternative(html_body, "text/html")
            message.send()
            responseData = {}
            return HttpResponse(json.dumps(responseData), content_type="application/json")
        else:
            return HttpResponseBadRequest()


class BalotiContestListView(TemplateView):
    """
    Contest List View
    """

    def get(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns contest_list.html html file
        """
        open_list = []
        closed_list = []
        current_language = get_language()
        open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open",language__iso=current_language).order_by('-parent_contest_id__start')
        for open_contest in open_contests:
            open_list.append(getParentDetails(open_contest))
        closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed",language__iso=current_language).order_by('-parent_contest_id__end')
        for closed_contest in closed_contests:
            closed_list.append(getParentDetails(closed_contest))
        return render(request, 'contest_list.html',{"open_contests": open_list, "closed_contests": closed_list})

class BalotiContestListSortView(TemplateView):
    """
    Contest List View
    """

    def get(self, request, sort):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns contest_list.html html file
        """
        open_list = []
        closed_list = []
        current_language = get_language()
        if sort == 'asc':
            open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open",language__iso=current_language).order_by('parent_contest_id__actual_start')
            closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed",language__iso=current_language).order_by('parent_contest_id__actual_end')
        else:
            open_contests = ParentContesti18n.objects.filter(parent_contest_id__status="open", language__iso=current_language).order_by('-parent_contest_id__actual_start')
            closed_contests = ParentContesti18n.objects.filter(parent_contest_id__status="closed", language__iso=current_language).order_by('-parent_contest_id__actual_end')
        for open_contest in open_contests:
            open_list.append(getParentDetails(open_contest))
        for closed_contest in closed_contests:
            closed_list.append(getParentDetails(closed_contest))
        return render(request, 'contest_list.html',{"open_contests": open_list, "closed_contests": closed_list})


class BalotiContestDetailView(TemplateView):
    """
    Contest Detail View
    """
    
    def get(self, request, id):
        """
        Args:
            request (Request): Http request object
            id: Contest UID

        Returns:
            html : returns contest_details.html html file
        """
        current_language = get_language()
        contest = ParentContesti18n.objects.filter(parent_contest_id__uid=id, language__iso=current_language)
        child_contests = Contesti18n.objects.filter(
                parent=contest.first().parent_contest_id,
                language__iso=current_language
                ).distinct('id')
        date_string = contest.first().parent_contest_id.end.strftime("%m/%d/")
        return render(request, 'contest_details.html',{"contest": contest.first(), "date": str(date_string), "child_contests": child_contests})


class BalotiContestResultView(TemplateView):
    """
    Contest Result View
    """

    def get(self, request, id):
        """
        Args:
            request (Request): Http request object
            id: Contest UID

        Returns:
            html : returns contest_results.html html file
        """
        current_language = get_language()
        contest = Contesti18n.objects.filter(contest_id=id, language__iso=current_language).first()
        return render(request, 'contest_results.html',{"contest": contest})


class BalotiContestChoicesView(TemplateView):
    """
    Contest Choices View
    """
    
    def get(self, request, id):
        """
        Args:
            request (Request): Http request object
            id: Candidate UID

        Returns:
            html : returns contest_vote_choices.html html file
        """
        data = []
        current_language = get_language()
        language = Language.objects.filter(iso=current_language).first()
        contest = Contesti18n.objects.filter(contest_id=id, language__iso=current_language)
        if contest:

baloti_djelectionguard/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
{% load static %}
{% load sass_tags %}

<head>
    <meta property="fb:app_id" content="480123580439004" />
    <meta property="og:image" content="https://uat.baloti.org/static/images/thumbnail.png"/>
    <meta property="og:type" content="website">
    <meta property="og:description" content="Baloti Voting webiste">
    <meta property='og:url' content='https://uat.baloti.org//baloti/'/>
    <meta property='og:title' content='Baloti'/>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>baloti</title>
    <meta name="description" content="Baloti Voting webiste">
    <!-- <meta property="og:locale" content="en_US" />
    <meta property="og:locale:alternate" content="fr_CH" /> -->
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- <link href="{% sass_src 'scss/main.scss' %}" rel="stylesheet" type="text/css" /> -->
    <script src="/static/js/jquery-3.5.1.min.js"></script>
    <script src="/static/js/slick.min.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/chart.min.js"></script>
    <script src="/static/js/app-main.js"></script>
    <script src="/static/js/app-common.js"></script>
</head>

<body>
    <div class="app">
        <!-- Topbar -->
        {% include 'layout/header.html' %}
        <!-- End of Topbar -->
     
        {% block body %}
        {% endblock body %}

        <!-- Footer -->
        {% include 'layout/footer.html' %}
        <!-- End of Footer -->
    </div>
</body>

</html>

baloti_djelectionguard/templates/layout/footer.html
{% load static %}
{% load static i18n %}

<footer class="app-footer">
    <div class="container">
      <div class="row">
          <div class="col-sm-3">
              <a href="#" class="app-footer__logo">
                  <img src="/static/images/logo-footer.png" width="120" alt="">
              </a>
          </div> 
          <div class="col-sm-9">
              <ul class="app-footer-link list-unstyled">
                  <li><a href={% url 'baloti_djelectionguard:Index' %}></li>
                  <li><a href={% url 'baloti_djelectionguard:ContestList' %}>{% trans "Referendum Votes" %}</a></li>
                  <li><a href={% url 'balotidjelectionguard:Illustration' %}>{% trans "Illustrations" %}</a></li>
                 <!--  <li><a href="#">Survey</a></li>
                  <li><a href="#">Results</a></li>
                  <li><a href="#">Picture dictionary</a></li> -->
                  <!-- <li><a href="/about-us">About Us</a></li> -->
                  <li><a href={% url 'balotidjelectionguard:Disclaimer' %}>{% trans "Disclaimer" %}</a></li>
                  <li><a target = "_blank" href="/static/pdf/baloti_User_Manual.pdf">{% trans "User Manual" %}</a></li>
              </ul>
          </div>
      </div>
      <div class="app-footer__bottom">
          <div class="row">
              <div class="col-sm-6">
                  <a class="app-email">copyright@baloti.org</a>
              </div>
            <!--   <div class="col-sm-6">
                  <ul class="app-social-link list-unstyled">
                      <li>
                          <a href=""><span class="app-icon icon-facebook-sm"></span></a>
                      </li>
                      <li>
                          <a href=""><span class="app-icon icon-twiter"></span></a>
                      </li>
                  </ul>
              </div> -->
          </div>
      </div>
    </div>
</footer>

baloti_djelectionguard/templates/layout/header.html
{% load static %}
{% load static i18n %}
{% load sass_tags %}
{% get_current_language as LANGUAGE%}
{% load base_tags %}
<header class="app-header">
    <div class="app-header__wrapper d-flex align-items-center">
        <a href={% url 'baloti_djelectionguard:Index' %} class="app-logo">
            <img src="/static/images/logo.svg" alt="">
        </a>
        <ul class="app-header-nav main list-unstyled d-flex align-items-center ml-auto">
            <li>
                <div class="dropdown">
                {% displayLanguageCode LANGUAGE as code %}
                <a style="text-transform:uppercase" class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{code}}</a>

                <ul class="dropdown-menu dropdown-menu--device dropdown-menu-end">
                    <div class="dropdown-menu__header">
                        <span class="dropdown-menu__title">Languages</span>
                        <span class="app-icon icon-close-bold m-pointer"></span>
                    </div>
                    {% get_available_languages as LANGUAGES %}
                    {% for lang_code, lang_name in LANGUAGES %}
                    {% if LANGUAGE != lang_code %}
                    {% displayLanguageName lang_code lang_name as name %}
                    <li>
                        <a id="{{lang_code}}" class="dropdown-item" href="/{{ lang_code }}{{ request.get_full_path|slice:'3:' }}">{{name}}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            </li>
            <li class="app-menu">
                <input id="menu__toggle" class="app-menu-toggle" type="checkbox">
                <label class="app-menu-btn" for="menu__toggle">
                    <span></span>
                </label>
                <div class="app-menu-drawer">
                    <ul class="app-menu-list list-unstyled">
                        <li>
                            <a href={% url 'baloti_djelectionguard:Index' %}>Home</a>
                        </li>
                        <li>
                            <a href={% url 'baloti_djelectionguard:ContestList' %}>{% trans "Referendum Votes" %}</a>
                        </li>
                        <li>
                            <a href={% url 'balotidjelectionguard:Illustration' %}>{% trans "Illustrations" %}</a>
                        </li>
                        <!-- <li>
                            <a href="/about-us">About Us</a>
                        </li> -->
                        <li>
                            <a href={% url 'balotidjelectionguard:Disclaimer' %}>{% trans "Disclaimer" %}</a>
                        </li>
                    </ul>
                    <div class="app-menu-drawer__mobile">
                        {% if user.is_anonymous %}
                        <a href={% url 'baloti_auth:login' %} class="app-link">{% trans "Login" %}</a>
                        {% else %}
                        <details class="app-menu-drawer__profile">
                            <summary>
                                <span class="app-icon icon-profile"></span>
                                <div class="app-menu-drawer__profiletitle">
                                    <p class="m-0">{{user.email}}</p>
                                    <span class="app-menu-drawer__profilesetting">{% trans "Profile settings" %}</span>
                                </div>
                            </summary>
                            <ul class="list-unstyled app-loggedin__menulist">
                                <li>
                                    <a class="dropdown-item" href={% url 'baloti_auth:change-password' %}> <span class="app-icon icon-Security-Safes"></span> <span>{% trans "Change Password?" %}</span></a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-danger" href="#" data-bs-toggle="modal" data-bs-target="#deleteProfile"> <span class="app-icon icon-delete"></span> <span>{% trans "Delete profile" %}</span></a>
                                </li>
                            </ul>
                        </details>
                        
                          <a class="app-link" href="{% url 'baloti_auth:logout' %}?next={% url 'baloti_djelectionguard:ProcessSuccessIndex' 'logout' %}">{% trans "Logout" %}</a>
                        {% endif %}
                    </div>
                </div>
            </li>
            {% if user.is_anonymous %}
                <li class="app-loginbtn">
                    <a href={% url 'baloti_auth:login' %} class="btn btn-outline">{% trans "Login" %}</a>
                </li>
    
            {% else %}
                <li class="app-loggedin">
                    <div class="dropdown app-loggedin__dropdown">
                        <a class=" dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="app-icon icon-profile"></span>
                        </a>
                      
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-menu__header">
                                <p><span class="app-icon icon-mail"></span> <span>{{user.email}}</span></p>
                            </div>
                            <ul class="list-unstyled app-loggedin__menulist">
                                <li>
                                    <a class="dropdown-item" href={% url 'baloti_auth:change-password' %}> <span class="app-icon icon-Security-Safes"></span> <span>{% trans "Change Password" %}</span></a>
                                </li>
                                <li>
                                    <a class="dropdown-item text-danger" href="#" data-bs-toggle="modal" data-bs-target="#deleteProfile"> <span class="app-icon icon-delete"></span> <span>{% trans "Delete profile" %}</span></a>
                                </li>
                                <li>
                                    <a href="{% url 'baloti_auth:logout' %}?next={% url 'baloti_djelectionguard:ProcessSuccessIndex' 'logout' %}" class="btn btn-primary btn-primary--outlined btn-flex justify-content-center">{% trans "Logout" %}</a>
                                </li>
                            </ul>
                        </div>
                      </div>
                </li>
            {% endif %}
        </ul>
    </div>
   
</header>

<!-- Delete profile Modal -->
<div class="modal fade app-modal app-modal--deleteprofile" id="deleteProfile" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-body text-center">
           <div class="modal-confirmbox">
               <div class="app-circle app-circle--primary app-circle--lg border-white">
                    <span class="app-icon icon-delete"></span>
               </div>
                <h6 class="app-h6 modal-confirmbox__title">{% trans "Are you sure you want to delete your baloti account?" %}</h6>
                <div class="btn-inline-group">
                    <button class="btn btn-default btn-flex--inline btn-lg" data-bs-dismiss="modal">{% trans "NO" %}</button>
                    <button class="btn btn-primary btn-lg" id="deleteProfileStep2">{% trans "YES" %}</button>
                </div>
           </div>
           <div class="modal-confirmbox modal-confirmbox--step-2 d-none">
                <div class="app-circle app-circle--primary app-circle--lg border-white">
                    <span class="app-icon icon-delete"></span>
                </div>
                <h6 class="app-h6 modal-confirmbox__title">{% trans "Enter your password to confirm" %}</h6>
                <input id="idPassword" class="form-control" type="password">
                <input id="idusername" class="form-control" type="hidden" value="{{user}}">
                <p class="label label-danger d-none" id="userpassword_error">
                    {% trans "Invalid password" %}
                </p>
                <div class="btn-inline-group">
                    <button class="btn btn-default btn-flex--inline" data-bs-dismiss="modal">{% trans "CANCEL" %}</button>
                    <button class="btn btn-primary" id="deleteProfileConfirm">{% trans "CONFIRM" %}</button>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>

<script>
    $(document).ready(function(){
        var languageObject = '{{LANGUAGE}}';
        localStorage.setItem('languageObject', JSON.stringify(languageObject));
    });
</script>