baloti_auth/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "baloti_auth"
urlpatterns = [
    path('login/', BalotiLoginView.as_view(
        ), name="login"),
    path('logout/', auth_views.LogoutView.as_view(
                    ), name='logout'),
    path('signup/', BalotiSignupView.as_view(
        ), name="signup"),
    path('signup/mailsent/', BalotiSignupMailView.as_view(
        ), name="signup_mail"),
    path('modalsignup/mailsent/', BalotiModalSignupMailView.as_view(
        ), name="modalsignup_mail"),
    path(
        'change-password/',
        BalotiPasswordChangeView.as_view(
            template_name='change_password.html',
        ),
        name='change-password'
    ),
    path('password-reset/',
         BalotiPasswordResetView.as_view(
             template_name='password_reset.html',
             email_template_name='password_reset_email.html',
             html_email_template_name="password_reset_email.html",
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         BalotiPasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('delete/profile', BalotiDeleteProfileView.as_view(), name='deleteProfile'),
]

baloti_djelectionguard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', BalotiIndexView.as_view()),
    path('disclaimer', BalotiDisclaimerView.as_view()),
    path('about-us', BalotiAboutUsView.as_view()),
    path('contest/list/', BalotiContestListView.as_view()),
    path('contest/<str:id>', BalotiContestDetailView.as_view(), name='ContestDetails'),
    path('contest/vote/choices/<str:id>', BalotiContestChoicesView.as_view(), name='VoteChoices'),
    path('vote/<str:id>', VoteView.as_view(), name='casteVote'),
    path('contest/detail/<str:id>', BalotiContestDetailView.as_view(), name='viewContestDetails'),
    path('contest/result/<str:id>', BalotiContestResultView.as_view(), name='viewContestResult'),
    path('anonymous/vote/', BalotiAnonymousVoteView.as_view(), name='anonymousVote'),
    path('contest/vote/success/<str:id>', VoteSuccessView.as_view(), name='VoteSuccess'),
]

baloti_djelectionguard/urls/urls.py
from django.urls import path
from ..views import *

app_name = "baloti_djelectionguard"
urlpatterns = [
    path('', BalotiIndexView.as_view(), name="Index"),
    path('success/<str:process>', BalotiIndexView.as_view(), name="ProcessSuccessIndex"),
    path('contest/list/', BalotiContestListView.as_view(), name='ContestList'),
    path('contest/list/<str:sort>', BalotiContestListSortView.as_view(), name='ContestSortedList'),
    path('contest/<str:id>', BalotiContestDetailView.as_view(), name='ContestDetails'),
    path('contest/vote/choices/<str:id>', BalotiContestChoicesView.as_view(), name='VoteChoices'),
    path('vote/<str:id>', VoteView.as_view(), name='casteVote'),
    path('contest/detail/<str:id>', BalotiContestDetailView.as_view(), name='viewContestDetails'),
    path('contest/result/<str:id>', BalotiContestResultView.as_view(), name='viewContestResult'),
    path('anonymous/vote/', BalotiAnonymousVoteView.as_view(), name='anonymousVote'),
    path('contest/vote/success/<str:id>', VoteSuccessView.as_view(), name='VoteSuccess'),
]

electeez_common/urls.py
from django import http
from django.contrib import admin, messages
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url
from django.conf.urls.static import static
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.urls import include, path, reverse
from django.utils.decorators import method_decorator
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.templatetags.static import static as static_url
from django.contrib.auth import views as auth_views

from djlang.utils import gettext as _
from baloti_djelectionguard import cron_jobs

urlpatterns = [
    url(r'^favicon\.ico$', generic.RedirectView.as_view(url='/static/images/favicon.ico')),
]

cron_jobs.initialize_cron()

@method_decorator(csrf_exempt, name='dispatch')
class HomeView(generic.TemplateView):
    def dispatch(self, request, *args, **kwargs):
        url = reverse('login')

        if request.user.is_authenticated:
            url = reverse('parentcontest_list')

        elif home_page := getattr(settings, 'STATIC_HOME_PAGE', None):
            url = static_url(home_page)

        elif template := getattr(settings, 'HOME_TEMPLATE', None):
            self.template_name = template
            return super().dispatch(request, *args, **kwargs)

        return http.HttpResponseRedirect(url)

    def post(self, request, *args, **kwargs):
        if 'inputEmail' in request.POST:
            messages.success(
                request,
                _('You have successfully subscribed to %(app)s mailing list',
                    app=_('Neuilly Vote')
                )
            )
        return self.get(request, *args, **kwargs)


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('electeez_auth.urls')),
    path('contest/', include('djelectionguard.urls')),
    path('tezos/', include('djelectionguard_tezos.views')),
    path('track/', include('djelectionguard_tracker.views')),
    path('lang/', include('djlang.views')),
    path('electis/', HomeView.as_view(), name='home'),
    path('baloti/', include(('baloti_auth.urls', 'baloti'), namespace="baloti"), name='baloti'),
    path('baloti/', include(('baloti_djelectionguard.urls.urls', 'baloti_djelectionguard'), namespace="baloti_djelectionguard"), name='baloti_djelectionguard'),
    path('', include(('baloti_djelectionguard.urls.general_urls', 'general_djelectionguard'), namespace="general_djelectionguard"), name='general_djelectionguard'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
)

if settings.DEBUG:
    urlpatterns.append(
        path('bundles/', include('ryzom_django.bundle')),
    )


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns('/static/')
urlpatterns += staticfiles_urlpatterns('/public/electis')
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

neuilly/urls.py
from electeez_common.urls import *


class LegalView(generic.TemplateView):
    template_name = 'legal'


class DataPolicyView(generic.TemplateView):
    template_name = 'policy'


class CookieView(generic.TemplateView):
    template_name = 'cookies'


class FAQView(generic.TemplateView):
    template_name = 'faq'


urlpatterns += i18n_patterns(
    path('legal/', LegalView.as_view(), name='legal'),
    path('policy/', DataPolicyView.as_view(), name='policy'),
    path('cookies/', CookieView.as_view(), name='cookies'),
    path('faq/', FAQView.as_view(), name='faq'),
)

baloti_auth/models.py
from django.db import models

# Create your models here.

baloti_auth/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.forms import (
   SetPasswordForm,
)
from django.utils.translation import gettext, gettext_lazy as _


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)


class PasswordChangeForm(SetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = {
        **SetPasswordForm.error_messages,
        'password_incorrect': _("Your old password was entered incorrectly. Please enter it again."),
    }

baloti_auth/views.py
import json
from django.utils.translation import get_language
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from baloti_auth.forms import LoginForm
from django.views.generic import TemplateView
from django.contrib import messages
from django.conf import settings
from djlang.utils import gettext as _
from electeez_auth.models import User
import random
import string
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.http import *
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

class BalotiLoginView(LoginView):

    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', context={'form': form})

    def post(self, request):
        error = ''
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                try:
                    login(request, user)
                    return HttpResponseRedirect('/' + get_language() + '/baloti/success/login')
                    # return render(request, 'index.html',{"contests": contests, "login":True})
                except Exception as err:
                    error = _("Your username and password didn't match. Please try again.")
            else:
                user = User.objects.filter(email=username, first_login=False)
                if user:
                    user = user.first()
                    user.is_active = True
                    user.first_login = True
                    user.save()
                try:
                    user = authenticate(username=username, password=password)
                    login(request, user)
                    return HttpResponseRedirect('/' + get_language() + '/baloti/success/registration')
                except Exception as err:
                    error = _("Your username and password didn't match. Please try again.")
                else:
                    error = _("Login failed!")
        return render(request, 'login.html', {"error":error})

def home(request):
    """Home View
 
     Args:
         request (Request): Http request object
     Returns:
         html : returns home.html html file
     """
    return render(request, 'home.html')

class BalotiSignupView(TemplateView):
    """
    Baloti Signup View
    """
    template_name = "signup.html"


def signupMailSent(self, email, password):
    subject = _('Baloti Registration Information')
    email_from = settings.DEFAULT_FROM_EMAIL
    login_url = settings.BASE_URL + '/' + get_language() + '/baloti/login/'
    merge_data = {
                'username': email,
                'password': password,
                'login_url': login_url
                }
    print('merge_data=================', merge_data)
    html_body = render_to_string("signup_mail.html", merge_data)

    message = EmailMultiAlternatives(
       subject=subject,
       body="mail testing",
       from_email=email_from,
       to=[email],
    )
    message.attach_alternative(html_body, "text/html")
    message.send()

class BalotiSignupMailView(TemplateView):
    """
    Baloti Signup Mail View
    """

    def post(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns signup_success.html html file
        """
        email = request.POST.get('email')
        password = ''.join(random.choices(string.ascii_uppercase + string.digits, k=7))
        try:
            user = User.objects.filter(email=email, is_active=False)
            if user:
                user = user.first()
                user.set_password(password)
                user.first_login = False
                user.save()
            else:
                user = User.objects.create_user(email, password)
                user.is_active = False
                user.first_login = False
                user.save()
        except Exception as err:
            return render(request, 'signup.html', {"email": email, "error":err})
        signupMailSent(self, email, password)
        return render(request, 'signup_success.html')


class BalotiModalSignupMailView(TemplateView):
    """
    Baloti Signup Mail View
    """

    def post(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns signup_success.html html file
        """
        email = request.POST.get('email')
        password = ''.join(random.choices(string.ascii_uppercase + string.digits, k=7))
        try:
            user = User.objects.filter(email=email, is_active=False)
            if user:
                user = user.first()
                user.set_password(password)
                user.first_login = False
                user.save()
            else:
                user = User.objects.create_user(email, password)
                user.is_active = False
                user.first_login = False
                user.save()
        except Exception as err:
            return HttpResponseBadRequest()
        signupMailSent(self, email, password)
        return render(request, 'signup_success.html')


class BalotiDeleteProfileView(TemplateView):
    """
    Contest Anonymous Vote
    """

    def post(self, request):
        """
        Args:
            request (Request): Http request object

        Returns:
            html : returns login.html html file
        """
        password = request.POST.get('password', None)
        username = request.POST.get('username')
        user = request.user
        if not user.check_password(password):
            return HttpResponse({'invalid_password':True}, status=200)
        user.is_active = False
        user.save()
        responseData = {}
        return HttpResponse(json.dumps(responseData), content_type="application/json")


class BalotiPasswordChangeView(LoginRequiredMixin, auth_views.PasswordChangeView):
    success_url = reverse_lazy('baloti_djelectionguard:ProcessSuccessIndex', kwargs={'process': 'changepassword'})

class BalotiPasswordResetView(auth_views.PasswordResetView):
    success_url = reverse_lazy('baloti_auth:password_reset_done')

class BalotiPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('baloti_auth:password_reset_complete')

baloti_auth/templates/change_password.html
{% extends 'layout/base.html' %}
{% load static %}
{% load static i18n %}
{% load referendum %}
{% load issues %}
{% block body %}    


<section class="app-login">
    <div class="app-login__img">
        <img src="/static/images/login-img.png" alt="">
    </div>
    <div class="container">
        <div class="row flex-row-reverse">
            <div class="col-sm-12 col-xl-5">
                <div class="app-login__box">
                    <form id="change_password-form" method="post" action="{% url 'baloti:change-password' %}">
                    {% csrf_token %}
                        <div class="app-login__logo">
                            <img src="/static/images/logo.svg" alt="">
                        </div>
                       
                        <p class="app-login__subhead">{%trans "Change Password" %}</p>

                        
                        <div class="app-form">
                            <div class="app-form__control app-form__control--password">
                                <input id="id_old_password" name="old_password" 
                                           type="password" class="form-control" placeholder=" ">
                                <label for="id_old_password" class="app-form__label">{%trans "Old Password" %}</label>
                                <span id="showHidePassword" class="app-icon icon-view show-hide-password"></span>
                            </div>
                            <div class="app-form__control app-form__control--password">
                                <input id="new_password1" name="new_password1" 
                                           type="password" class="form-control" placeholder=" ">
                                <label for="new_password1" class="app-form__label">{%trans "New Password" %}</label>
                                <span id="showHidePassword" class="app-icon icon-view show-hide-password"></span>
                            </div>
                            <div class="app-form__control app-form__control--password">
                                <input id="new_password2" name="new_password2" 
                                           type="password" class="form-control" placeholder=" ">
                                <label for="new_password2" class="app-form__label">{%trans "New Password Confirmation" %}</label>
                                <span id="showHidePassword" class="app-icon icon-view show-hide-password"></span>
                            </div>


                            {% if form.errors %}
                            {% for error in form.errors.new_password2 %}
                                <p class=" label label-danger label-danger--light">
                                     {{error}}
                                </p>
                            {% endfor %}
                            {% endif %}


                            <button type="submit" class="btn btn-primary btn-block btn-md--small">{%trans "CONTINUE" %}</button>
                            <p class="app-login__createaccount"></p>
                        </div>

                        <a class="btn btn-link btn-flex btn-back" href="javascript:window.history.back()"><span class="app-icon icon-arrow"></span> <span>{%trans "Back" %}</span></a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

baloti_auth/templates/contest_details.html
{% extends 'base.html' %}
{% block title %} Elections {% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-8 mx-auto social-container my-2 order-md-1">

    </div>
    <ul>
        {% for u in contests %}

            <button class="btn btn-primary mb-2">
                <a href={% url 'baloti:VoteChoices' id=u.id %}>VOTE NOW</a><br>
            </button>
            
        {% endfor %}
    </ul>
</div>
{% endblock %}

baloti_auth/templates/login.html
{% load static %}
{% load static i18n %}
{% load sass_tags %}
{% load base_tags %}
{% get_current_language as LANGUAGE%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>baloti</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="app">
         <!-- Header Section -->
         <header class="app-header app-header--login">
             <div class="container d-flex align-items-center">
                <a href="#" class="app-logo app-logo--login">
                    <img src="/static/images/logo.svg" alt="">
                </a>
                <ul class="app-header-nav list-unstyled d-flex align-items-center ml-auto">
                    <li>
                        <div class="dropdown">
                            {% displayLanguageCode LANGUAGE as code %}
                            <a style="text-transform:uppercase" class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{code}}</a>

                            <ul class="dropdown-menu dropdown-menu--device dropdown-menu-end">
                                <div class="dropdown-menu__header">
                                    <span class="dropdown-menu__title">Languages</span>
                                    <span class="app-icon icon-close-bold m-pointer"></span>
                                </div>
                                {% get_available_languages as LANGUAGES %}
                                {% for lang_code, lang_name in LANGUAGES %}
                                {% if LANGUAGE != lang_code %}
                                {% displayLanguageName lang_code lang_name as name %}
                                <li>
                                    <a id="{{lang_code}}"  class="dropdown-item" href="/{{ lang_code }}{{ request.get_full_path|slice:'3:' }}">{{name}}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
             </div>
           
        </header>


        <section class="app-login">
            <div class="app-login__img">
                <img src="/static/images/login-img.png" alt="">
            </div>
            <div class="container">
                <div class="row flex-row-reverse">
                    <div class="col-sm-12 col-xl-5">
                        <div class="app-login__box">
                            <form id="login-form" method="post" action="{% url 'baloti:login' %}">
                            {% csrf_token %}
                                <div class="app-login__logo">
                                    <img src="/static/images/logo.svg" alt="">
                                </div>
                                <h3 class="app-login__heading">
                                    {%trans "Welcome to baloti!" %}
                                </h3>
                                <p class="app-login__subhead">{%trans "Login to your account" %}</p>

                                <div class="app-login__btn-group">
                                    <a class="btn btn-facebook btn-block" href="{% url 'social:begin' 'facebook' %}?next={% url 'baloti_djelectionguard:ProcessSuccessIndex' 'login' %}"><span class="app-icon icon-facebook-box"></span> <span>{%trans "Continue with Facebook" %}</span></a>
                                    <!-- <button class="btn btn-google btn-block"><span class="app-icon"><img src="/static/images/google.svg" alt=""></span> <span>Continue with Google</span></button>
                                    <button class="btn btn-apple btn-block"><span class="app-icon icon-apple"></span> <span>Continue with Apple</span></button> -->
                                </div>
                                
                                <p class="app-sepeartor"><span>or</span></p>
                                <div class="app-form">
                                    <div class="app-form__control">
                                        <input id="id_username" name="username" 
                                                   type="text" class="form-control" placeholder=" ">
                                        <label for="id_username" class="app-form__label">{%trans "Email address" %}</label>
                                    </div>
                                    <div class="app-form__control app-form__control--password">
                                        <input id="id_password" name="password" 
                                                   type="password" class="form-control" placeholder=" ">
                                        <label for="id_password" class="app-form__label">{%trans "Password" %}</label>
                                        <span id="showHidePassword" class="app-icon icon-view show-hide-password"></span>
                                    </div>
                                    {% if error %}
                                        <p class=" label label-danger label-danger--light">
                                            {{error}}
                                        </p>
                                    {% endif %}


                                    <a href={% url 'baloti_auth:password_reset' %} class="app-link app-link--forget-password">{%trans "Forgot password?" %}</a>
                                    <button type="submit" class="btn btn-primary btn-block btn-md--small">{%trans "CONTINUE" %}</button>
                                    <p class="app-login__createaccount"><span>{%trans "Not registered yet?" %}</span> <a href={% url 'baloti_auth:signup' %} class="app-link">{%trans "Create an account now!" %}</a> </p>


                                </div>

                                <a class="btn btn-link btn-flex btn-back" href="javascript:window.history.back()"><span class="app-icon icon-arrow"></span> <span>{%trans "Back" %}</span></a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>


    </div>

<script src="/static/js/jquery-3.5.1.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/app-main.js"></script>
<script src="/static/js/app-common.js"></script>
</body>
</html>

baloti_auth/templates/signup.html
{% load static %}
{% load static i18n %}
{% load sass_tags %}
{% load base_tags %}
{% get_current_language as LANGUAGE%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>baloti</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="app">
         <!-- Header Section -->
         <header class="app-header app-header--login">
             <div class="container d-flex align-items-center">
                <a href="#" class="app-logo app-logo--login">
                    <img src="/static/images/logo.svg" alt="">
                </a>
                <ul class="app-header-nav list-unstyled d-flex align-items-center ml-auto">
                    <li>
                        <div class="dropdown">
                            {% displayLanguageCode LANGUAGE as code %}
                            <a style="text-transform:uppercase" class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{code}}</a>

                            <ul class="dropdown-menu dropdown-menu--device dropdown-menu-end">
                                <div class="dropdown-menu__header">
                                    <span class="dropdown-menu__title">Languages</span>
                                    <span class="app-icon icon-close-bold m-pointer"></span>
                                </div>
                                {% get_available_languages as LANGUAGES %}
                                {% for lang_code, lang_name in LANGUAGES %}
                                {% if LANGUAGE != lang_code %}
                                {% displayLanguageName lang_code lang_name as name %}
                                <li>
                                    <a id="{{lang_code}}" class="dropdown-item" href="/{{ lang_code }}{{ request.get_full_path|slice:'3:' }}">{{name}}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
             </div>
            
        </header>


        <section class="app-login">
            <div class="app-login__img">
                <img src="/static/images/login-img.png" alt="">
            </div>
            <div class="container">
                <div class="row flex-row-reverse">
                    <div class="col-sm-12 col-xl-5">
                        <div class="app-login__box">
                            <form id="login-form" method="post" action="{% url 'baloti:signup_mail' %}">
                            {% csrf_token %}
                            <div class="app-login__logo">
                                <img src="/static/images/logo.svg" alt="">
                            </div>
                            <h3 class="app-login__heading">
                                {%trans "Create account!" %}

                            </h3>
                            <p class="app-login__subhead">{%trans "You can register with your social login or email address." %}</p>
                            <div class="app-login__btn-group">
                                <a class="btn btn-facebook btn-block" href="{% url 'social:begin' 'facebook' %}?next={% url 'baloti_djelectionguard:ProcessSuccessIndex' 'login' %}"><span class="app-icon icon-facebook-box"></span> <span>{%trans "Continue with Facebook" %}</span></a>
                               <!--  <button class="btn btn-google btn-block"><span class="app-icon"><img src="/static/images/google.svg" alt=""></span> <span>Continue with Google</span></button>
                                <button class="btn btn-apple btn-block"><span class="app-icon icon-apple"></span> <span>Continue with Apple</span></button> -->
                            </div>
                            
                            <p class="app-sepeartor"><span>or</span></p>
                            <div class="app-form">
                                <form>
                                    <div class="app-form__control">
                                        {% if email %}
                                        <input type="email" name="email" id="exampleInputEmail1" value={{email}} aria-describedby="emailHelp" placeholder=" "/>
                                        {% else %}
                                        <input type="email" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder=" "/>
                                        {% endif %}
                                        <label for="exampleInputEmail1" class="app-form__label">{%trans "Email address" %}</label>
                                        <div class="app-form__msg">
                                            <p class="text-danger m-0">{{error}}</p>
                                            <p>{%trans "We will send you the registration link to the email address you entered." %}</p>
                                        </div>
                                    </div>
                                    
                                    <button type="submit" class="btn btn-primary btn-block btn-md--small">{%trans "SEND" %}</button>
                                </form>
                                <p class="app-login__createaccount"><span>{%trans "Already have an account?" %}</span> <a href={% url 'baloti_auth:login' %} class="app-link">{%trans "Login here!" %}</a> </p>

                            </div>
                            <a class="btn btn-link btn-flex btn-back" href="javascript:window.history.back()"><span class="app-icon icon-arrow"></span> <span>{%trans "Back" %}</span></a>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>


    </div>

<script src="/static/js/jquery-3.5.1.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/app-main.js"></script>
<script src="/static/js/app-common.js"></script>
</body>
</html>